// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6527.ShortSirKitTest;

import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import org.usfirst.frc6527.ShortSirKitTest.commands.*;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.ADXRS450_Gyro;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

    Command autonomousCommand;

    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    
    public XboxController xboxController;
    public Encoder encL;
    public Encoder encR;
    public VictorSP victorSPL;
    public VictorSP victorSPR;
    public int counter;
    public int stage;
    public double gyro_offset;
    public boolean reverse_toggle;
    public boolean reverse;
    public int control_scheme;
    public boolean control_toggle;
    public Servo camservo;
    public Spark dumper;
    public Spark winch;
    public ADXRS450_Gyro gyro; 
    
    public void robotInit() {
    RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        /* OI must be constructed after subsystems. If the OI creates Commands
        * (which it very likely will), subsystems are not guaranteed to be
        * constructed yet. Thus, their requires() statements may grab null
        * pointers. Bad news. Don't move it.
        */
        oi = new OI();

        // instantiate the command used for the autonomous period
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

        autonomousCommand = new AutonomousCommand();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        this.xboxController = new XboxController(0);
        this.victorSPL = new VictorSP(1);
        this.victorSPR = new VictorSP(0);
        this.dumper = new Spark(3);
        this.winch = new Spark(4);
        this.encL = new Encoder(2,3);
        this.encR = new Encoder(0,1);
        this.counter = 0;
        this.stage = 0;
        this.gyro_offset = 0.0;
        this.reverse_toggle = true;
        this.control_scheme = 0;
        this.control_toggle = true;
        this.reverse = false;
        this.camservo = new Servo(2);
        this.gyro = new ADXRS450_Gyro();
        gyro.calibrate();
        encL.setReverseDirection(true);
        encR.setReverseDirection(true);
        CameraServer.getInstance().startAutomaticCapture(0);
        CameraServer.getInstance().startAutomaticCapture(1);
        
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    public void disabledInit(){
    	encR.reset();
    	encL.reset();
    	encL.setReverseDirection(true);
        encR.setReverseDirection(true);

    }

    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    public void autonomousInit() {
        // schedule the autonomous command (example)
    	counter = -1;encL.reset(); encR.reset();stage = 0;
    	encL.setReverseDirection(true);
        encR.setReverseDirection(true);
        if (autonomousCommand != null) autonomousCommand.start();
        
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
        System.out.println(stage);
        double xAxis = 0;
    	double yAxis = 0;
        switch (stage) {
	        case 0:
		        	//if (encR.get() > counter*5) victorSPR.set(-0.45);
			        xAxis = 0.0;
			        yAxis = 1.0/6.0;
			        if ((encL.get() + encR.get()) / 2 < 3500) {stage = 1; counter = 0; encL.reset(); encR.reset();victorSPL.set(0);victorSPR.set(0);}
			        /*
			        if (encL.get() > counter*5) victorSPL.set(-0.45);
			        else victorSPL.set(-0.15);
			        if ((encL.get() <= counter*5) && (encR.get() <= counter*5) && (counter > -700)) counter -= 1;//284
			        else if (counter <= -700) {stage = 1; counter = 0; encL.reset(); encR.reset();victorSPL.set(0);victorSPR.set(0);}*/
			break;/*
	        case 1:
		        	if (encR.get() > counter*5) victorSPR.set(-0.45);
			        else victorSPR.set(-0.20);
			        if (encL.get() < counter*-5) victorSPL.set(0.45);
			        else victorSPL.set(0.20);
			        if ((encL.get() >= counter*-5) && (encR.get() <= counter*5) && (counter > -30)) counter -= 1;
			        else if (counter <= -30) {stage = 2; counter = 0; encL.reset(); encR.reset();victorSPL.set(0);victorSPR.set(0);}
		    break;
	        case 2:
	        	if (encR.get() > counter*5) victorSPR.set(-0.3);
		        else victorSPR.set(-0.15);
		        if (encL.get() > counter*5) victorSPL.set(-0.3);
		        else victorSPL.set(-0.15);
		        if ((encL.get() <= counter*5) && (encR.get() <= counter*5) && (counter > -90)) counter -= 1;
		        else if (counter <= -90) {stage = 3; counter = 0; encL.reset(); encR.reset();victorSPL.set(0);victorSPR.set(0);}
		    break;*/
        	}
			gyro_offset += xAxis / 9;
            
            xAxis += gyro.getAngle() / -180 + gyro_offset;
            
            //script to actually control the motors
            //System.out.println(xAxis);
            victorSPL.set(yAxis - xAxis);
        	victorSPR.set(yAxis + xAxis);
        	
        	//reset gyro if greater or less than 10 degrees
        	if (gyro.getAngle() > 10 || gyro.getAngle() < -10) {
        		gyro_offset -= gyro.getAngle() / 180;
        		gyro.reset();
		        
        }
        
    }
    

    public void teleopInit() {
    	
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
        reverse = false;
        reverse_toggle = true;
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        if (xboxController.getRawButton(2)){
        	gyro_offset = 0;
    		gyro.reset();
        }
        System.out.println(gyro_offset);
        
        //script for dumper, winch and camera
        camservo.set(xboxController.getRawAxis(5) / 2 + 0.5);
        if (xboxController.getRawButton(4)) winch.set(1);
        else winch.set(0);
        if (xboxController.getRawButton(3)) dumper.set(0.5);
        else dumper.set(-0.5);
        
        if (control_toggle && xboxController.getRawButton(7)) {
        	control_toggle = false;
        	switch (control_scheme){
        	case 0:
        		control_scheme = 1;
        	break;
        	case 1:
        		control_scheme = 0;
        	break;
        	}
        	if (reverse) reverse = false;
        	else reverse = true;
        } else if(xboxController.getRawButton(7) == false) control_toggle = true;
        
        double yAxis = 0;
        double xAxis = 0;        
        
        switch (control_scheme){
    	case 0:
    		yAxis = xboxController.getRawAxis(1);
            xAxis = xboxController.getRawAxis(0);
    	break;
    	case 1:
    		yAxis = xboxController.getRawAxis(3) - xboxController.getRawAxis(2);
            xAxis = xboxController.getRawAxis(0);
    	break;
    	}
        if (yAxis < 0.15 && yAxis > -0.15) yAxis = 0;
        if (xAxis < 0.15 && xAxis > -0.15) xAxis = 0;
        
        int pov = xboxController.getPOV();
        if (-1 != pov) pov /= 45;
        if (!(xboxController.getRawButton(5) || xboxController.getRawButton(6) || -1 != pov)) {
        	xAxis /= 6;
        	yAxis /= 6;
        }else if (xboxController.getRawButton(6)) {
        	xAxis = 0.0;
        	yAxis = -0.9;
        }else if (xboxController.getRawButton(5)) {
        	xAxis /= 4;
        	yAxis /= 2;
        }else if (-1 != pov){
        	switch (pov) {
	        	case 0:	xAxis = 0;
	        			yAxis = -1.0/6.0;
	                	System.out.println(pov);
	        	break;
	        	case 1:	xAxis = 1.0/12.0;
    					yAxis = -1.0/12.0;
    			break;
	        	case 2:	xAxis = 1.0/6.0;
    					yAxis = 0;
    			break;
	        	case 3:	xAxis = 1.0/12.0;
						yAxis = 1.0/12.0;
    			break;
	        	case 4:	xAxis = 0;
    					yAxis = 1.0/6.0;
		    	break;
		    	case 5:	xAxis = -1.0/12.0;
    					yAxis = 1.0/12.0;
				break;
		    	case 6:	xAxis = -1.0/6.0;
    					yAxis = 0;
				break;
		    	case 7:	xAxis = -1.0/12.0;
    					yAxis = -1.0/12.0;
				break;
        }}
        	if (reverse_toggle && xboxController.getRawButton(8)) {
            	reverse_toggle = false;
            	if (reverse) reverse = false;
            	else reverse = true;
            } else if(xboxController.getRawButton(8) == false) reverse_toggle = true;
            if (reverse) yAxis *= -1;
            //if (xboxController.getRawButton(8)) yAxis *= -1;
            
            gyro_offset += xAxis / 9;
            
            xAxis += gyro.getAngle() / -180 + gyro_offset;
            
            //script to actually control the motors
            //System.out.println(xAxis);
            victorSPL.set(yAxis - xAxis);
        	victorSPR.set(yAxis + xAxis);
        	
        	//reset gyro if greater or less than 10 degrees
        	if (gyro.getAngle() > 10 || gyro.getAngle() < -10) {
        		//gyro_offset = 0;
        		gyro_offset += gyro.getAngle() / -180.0;
        		gyro.reset();

        	}
    }

    /**
     * This function is called periodically during test mode
     */
    public void testPeriodic() {
        LiveWindow.run();
    }
}